// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.4
// source: writer/v1/writer.proto

package writerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LocalBackupWriter_StartWrite_FullMethodName  = "/writer.v1.LocalBackupWriter/StartWrite"
	LocalBackupWriter_WriteFrames_FullMethodName = "/writer.v1.LocalBackupWriter/WriteFrames"
	LocalBackupWriter_CommitWrite_FullMethodName = "/writer.v1.LocalBackupWriter/CommitWrite"
	LocalBackupWriter_AbortWrite_FullMethodName  = "/writer.v1.LocalBackupWriter/AbortWrite"
)

// LocalBackupWriterClient is the client API for LocalBackupWriter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LocalBackupWriterClient interface {
	StartWrite(ctx context.Context, in *StartWriteRequest, opts ...grpc.CallOption) (*StartWriteResponse, error)
	WriteFrames(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WriteFrame, WriteFramesSummary], error)
	CommitWrite(ctx context.Context, in *CommitWriteRequest, opts ...grpc.CallOption) (*CommitWriteResponse, error)
	AbortWrite(ctx context.Context, in *AbortWriteRequest, opts ...grpc.CallOption) (*AbortWriteResponse, error)
}

type localBackupWriterClient struct {
	cc grpc.ClientConnInterface
}

func NewLocalBackupWriterClient(cc grpc.ClientConnInterface) LocalBackupWriterClient {
	return &localBackupWriterClient{cc}
}

func (c *localBackupWriterClient) StartWrite(ctx context.Context, in *StartWriteRequest, opts ...grpc.CallOption) (*StartWriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartWriteResponse)
	err := c.cc.Invoke(ctx, LocalBackupWriter_StartWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localBackupWriterClient) WriteFrames(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WriteFrame, WriteFramesSummary], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LocalBackupWriter_ServiceDesc.Streams[0], LocalBackupWriter_WriteFrames_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WriteFrame, WriteFramesSummary]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LocalBackupWriter_WriteFramesClient = grpc.ClientStreamingClient[WriteFrame, WriteFramesSummary]

func (c *localBackupWriterClient) CommitWrite(ctx context.Context, in *CommitWriteRequest, opts ...grpc.CallOption) (*CommitWriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitWriteResponse)
	err := c.cc.Invoke(ctx, LocalBackupWriter_CommitWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localBackupWriterClient) AbortWrite(ctx context.Context, in *AbortWriteRequest, opts ...grpc.CallOption) (*AbortWriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbortWriteResponse)
	err := c.cc.Invoke(ctx, LocalBackupWriter_AbortWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LocalBackupWriterServer is the server API for LocalBackupWriter service.
// All implementations must embed UnimplementedLocalBackupWriterServer
// for forward compatibility.
type LocalBackupWriterServer interface {
	StartWrite(context.Context, *StartWriteRequest) (*StartWriteResponse, error)
	WriteFrames(grpc.ClientStreamingServer[WriteFrame, WriteFramesSummary]) error
	CommitWrite(context.Context, *CommitWriteRequest) (*CommitWriteResponse, error)
	AbortWrite(context.Context, *AbortWriteRequest) (*AbortWriteResponse, error)
	mustEmbedUnimplementedLocalBackupWriterServer()
}

// UnimplementedLocalBackupWriterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLocalBackupWriterServer struct{}

func (UnimplementedLocalBackupWriterServer) StartWrite(context.Context, *StartWriteRequest) (*StartWriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartWrite not implemented")
}
func (UnimplementedLocalBackupWriterServer) WriteFrames(grpc.ClientStreamingServer[WriteFrame, WriteFramesSummary]) error {
	return status.Errorf(codes.Unimplemented, "method WriteFrames not implemented")
}
func (UnimplementedLocalBackupWriterServer) CommitWrite(context.Context, *CommitWriteRequest) (*CommitWriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitWrite not implemented")
}
func (UnimplementedLocalBackupWriterServer) AbortWrite(context.Context, *AbortWriteRequest) (*AbortWriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AbortWrite not implemented")
}
func (UnimplementedLocalBackupWriterServer) mustEmbedUnimplementedLocalBackupWriterServer() {}
func (UnimplementedLocalBackupWriterServer) testEmbeddedByValue()                           {}

// UnsafeLocalBackupWriterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LocalBackupWriterServer will
// result in compilation errors.
type UnsafeLocalBackupWriterServer interface {
	mustEmbedUnimplementedLocalBackupWriterServer()
}

func RegisterLocalBackupWriterServer(s grpc.ServiceRegistrar, srv LocalBackupWriterServer) {
	// If the following call pancis, it indicates UnimplementedLocalBackupWriterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LocalBackupWriter_ServiceDesc, srv)
}

func _LocalBackupWriter_StartWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalBackupWriterServer).StartWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalBackupWriter_StartWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalBackupWriterServer).StartWrite(ctx, req.(*StartWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalBackupWriter_WriteFrames_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LocalBackupWriterServer).WriteFrames(&grpc.GenericServerStream[WriteFrame, WriteFramesSummary]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LocalBackupWriter_WriteFramesServer = grpc.ClientStreamingServer[WriteFrame, WriteFramesSummary]

func _LocalBackupWriter_CommitWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalBackupWriterServer).CommitWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalBackupWriter_CommitWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalBackupWriterServer).CommitWrite(ctx, req.(*CommitWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalBackupWriter_AbortWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalBackupWriterServer).AbortWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalBackupWriter_AbortWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalBackupWriterServer).AbortWrite(ctx, req.(*AbortWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LocalBackupWriter_ServiceDesc is the grpc.ServiceDesc for LocalBackupWriter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LocalBackupWriter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "writer.v1.LocalBackupWriter",
	HandlerType: (*LocalBackupWriterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartWrite",
			Handler:    _LocalBackupWriter_StartWrite_Handler,
		},
		{
			MethodName: "CommitWrite",
			Handler:    _LocalBackupWriter_CommitWrite_Handler,
		},
		{
			MethodName: "AbortWrite",
			Handler:    _LocalBackupWriter_AbortWrite_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WriteFrames",
			Handler:       _LocalBackupWriter_WriteFrames_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "writer/v1/writer.proto",
}
